[project]
name = "aimultibox"
version = "0.0.3"
requires-python = ">=3.11"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["aimultibox*"]
